use_frameworks!

platform :ios, '10.0'

target 'SocketEngine_Example' do
  pod 'SocketEngine', :path => '../'

  target 'SocketEngine_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
